// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmfrnvqvgorvbyrrscpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZnJudnF2Z29ydmJ5cnJzY3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjQ0NTIsImV4cCI6MjA2ODM0MDQ1Mn0.v6IBDQCPWCf4J0Y5_X8SZzKq0i_M90sNUB-TzpHun34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});